#!/bin/bash

GIT_ROOT="$(git rev-parse --show-toplevel)"
LINT_VERSION="v1.52.2"
LINT_BIN="$GIT_ROOT/.golangci-lint"
set -e

if [ ! -f "$LINT_BIN" ]; then
    echo "Downloading dependencies..."
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GIT_ROOT" "$LINT_VERSION"
	mv "$GIT_ROOT/golangci-lint" "$LINT_BIN"
fi

"$LINT_BIN" run -E gosec
