name: tests

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Run Revive Action by building from repository
      uses: morphy2k/revive-action@v1
      with:
        config: revive.toml

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make test
