name: Release

on:
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  release-please:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: go-env
