name: Verify

on:
  workflow_call:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: latest

    - name: Test
      run: make test
