name: Verify

on:
  workflow_call:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Test
      run: script/test
